// presentation.generated.mu — AUTOGENERATED. Do not edit.
// Regenerated from the compiled model. Author templates live in presentation/*.mu.

resources LibraryPresentation {

    // --- Icons: one geometry per distinct icon referenced by the model. ---
    include colored "resources/businessman.svg" as mm_icon_businessman

    // --- Embedded content (base64) — reserved for future assets. ---
}
